CONNECT 'jdbc:derby://localhost:1527/WM;user=WM;password=WM';

SELECT * FROM WM.ACCOUNT;
SELECT * FROM WM.PRODUCT;
SELECT * FROM WM.LOCATION;
SELECT * FROM WM.CONTRACTOR;
SELECT * FROM WM.STOCK;
SELECT * FROM WM.ISSUE;